language: php

sudo: false

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=MYSQL PDO=1 CORE_RELEASE=3.6
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.4
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.6
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --config `pwd`/_config.test.php
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit notification/tests
